<a href="https://colab.research.google.com/github/Thavatharani06/231801180_PODS/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([8, 9, 6, 2])

print(arr)

[8 9 6 2]


In [ ]:
my_list = list(range(10))
print(my_list)
print(type(my_list))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [ ]:
import numpy as np
import sys
S= range(1000)
print("Size of each element of list in bytes: ",sys.getsizeof(S))
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))
D= np.arange(1000)
print("Size of each element of Numpy array in bytes: ",D.itemsize)
print("Size of the whole Numpy array  in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of Numpy array in bytes:  8
Size of the whole Numpy array  in bytes:  8000


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print("Shape= ",data.shape)
print("Type= ",data.dtype)
print("Data = ", data)
print("\nAns1 = ",data * 10)
print("\nAns2= ",data+data)

Shape=  (2, 3)
Type=  float64
Data =  [[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

Ans1 =  [[ 15.  -1.  30.]
 [  0. -30.  65.]]

Ans2=  [[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


In [ ]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(type(arr))
print(arr)
print("\n", arr.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5]

 int64


In [ ]:
zeros_arr = np.zeros((5,2))
eros_arr = np.zeros(5)
print(zeros_arr)

zeros_arr = np.zeros((2,3))
print(zeros_arr)

print("Data type of the array: ",zeros_arr.dtype)

zeros_arr_int = np.zeros((3,3), dtype=np.int16)
print("\nArray of zeros with integer elements: \n",zeros_arr_int)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
Data type of the array:  float64

Array of zeros with integer elements: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ones_arr = np.ones(6)
print(ones_arr)

ones_arr = np.ones((3,2,4))
print("\n",ones_arr)
print("\n ndim= ",ones_arr.ndim)

print("\nData type of the array: ",ones_arr.dtype)

ones_arr_int = np.ones((2,2), dtype=np.int16)
print("\nArray of ones with integer elements: \n",ones_arr_int)

[1. 1. 1. 1. 1. 1.]

 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

 ndim=  3

Data type of the array:  float64

Array of ones with integer elements: 
 [[1 1]
 [1 1]]


In [ ]:
empty_arr = np.empty((2,3))
print(empty_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
empty_arr = np.empty((2,3))
print(empty_arr)
print("\nData type of the array: ",empty_arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]

Data type of the array:  float64


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

identity_matrix = np.eye(4)
print("\n",identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr = np.array([1, 2, 3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype(np.float64)
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  [1 2 3] int64
After converting:  [1. 2. 3.] float64


In [ ]:
arr = np.array(['1.1', '2.2', '-3.3'])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)

Before converting:  ['1.1' '2.2' '-3.3'] <U4
After converting:  [ 1.1  2.2 -3.3] float32


In [ ]:
arr1 = np.arange(10)
arr2 = np.random.randn(10)
print("array 1\n",arr1, arr1.dtype)
print("Array 2 \n",arr2, arr2.dtype)
new_arr = arr1.astype(arr2.dtype)
print("New Array \n",new_arr, new_arr.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
Array 2 
 [ 0.14473238  0.20795383 -1.19809951  1.72246819 -0.09100484  0.22698825
  1.01578953 -0.22448433  0.80241045 -1.54971263] float64
New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [ ]:
import numpy as np
a = np.array([1., 2., 3., 4.])
b = np.array([5., 6., 7., 8.])
print(a + b) # [ 6 8 10 12]
print(a - b) # [-4 -4 -4 -4]
print(a * b) # [ 5 12 21 32]
print(a / b) # [0.2 0.33333333 0.42857143 0.5 ]
print(a ** b) # [ 1 64 2187 65536]

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [ ]:
a = np.array([1., 2., 3., 4.])
print(a + 1) # [2. 3. 4. 5.]
print(a - 1) # [0. 1. 2. 3.]
print(a * 2) # [2. 4. 6. 8.]
print(a / 2) # [0.5 1. 1.5 2. ]
print(a ** 2) # [ 1. 4. 9. 16.]
print(1/a)

[2. 3. 4. 5.]
[0. 1. 2. 3.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]
[ 1.  4.  9. 16.]
[1.         0.5        0.33333333 0.25      ]
